"""empty message

Revision ID: b42b46902551
Revises: c4e080513254
Create Date: 2018-04-12 11:18:21.811112

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b42b46902551'
down_revision = 'c4e080513254'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('names',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=1024), nullable=True),
    sa.Column('status', sa.String(length=40), nullable=True),
    sa.Column('choice', sa.Integer(), nullable=True),
    sa.Column('nr_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['nr_id'], ['requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('names')
    # ### end Alembic commands ###
