"""empty message

Revision ID: c4e080513254
Revises: 
Create Date: 2018-04-12 02:57:44.917661

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4e080513254'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nr', sa.String(length=10), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('submitter', sa.String(length=80), nullable=True),
    sa.Column('corptype', sa.String(length=80), nullable=True),
    sa.Column('reqtype', sa.String(length=80), nullable=True),
    sa.Column('status', sa.String(length=40), nullable=True),
    sa.Column('staff', sa.String(length=40), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nr')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('requests')
    # ### end Alembic commands ###
